# Generated by Django 3.2.8 on 2021-10-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('height_cm', models.IntegerField()),
                ('weight_kg', models.FloatField()),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
