# Generated by Django 3.2.8 on 2021-10-08 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='chef',
            fields=[
                ('chef_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chef_name', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('food_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='nutritionist',
            fields=[
                ('nutritionist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone_no',
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('food_id', models.IntegerField()),
                ('food_quantity', models.IntegerField()),
                ('food_category', models.CharField(max_length=30)),
                ('total_price', models.IntegerField()),
                ('order_location', models.CharField(max_length=100)),
                ('order_status', models.CharField(max_length=30)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='deliveryman',
            fields=[
                ('delivery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bill', models.IntegerField()),
                ('order_location', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.customer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.order')),
            ],
        ),
    ]
