# Generated by Django 3.2.8 on 2021-10-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20211008_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total_price_taka',
        ),
    ]
